# Generated by Django 5.1.4 on 2025-01-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_password", models.CharField(max_length=128)),
                ("phone_number", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField()),
                (
                    "ssc_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/students/ssc/certificate/",
                    ),
                ),
                (
                    "ssc_transcript",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/students/ssc/certificate/",
                    ),
                ),
                (
                    "hsc_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/students/ssc/certificate/",
                    ),
                ),
                (
                    "hsc_transcript",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/students/ssc/certificate/",
                    ),
                ),
                (
                    "bachelor_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/students/ssc/certificate/",
                    ),
                ),
                (
                    "bachelor_transcript",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/students/ssc/certificate/",
                    ),
                ),
                (
                    "masters_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/students/ssc/certificate/",
                    ),
                ),
                (
                    "masters_transcript",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/students/ssc/certificate/",
                    ),
                ),
                (
                    "language_certificate",
                    models.FileField(null=True, upload_to="media/students/language/"),
                ),
                (
                    "bank_statement",
                    models.FileField(blank=True, upload_to="media/students/bank/"),
                ),
                (
                    "desired_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.countries",
                    ),
                ),
            ],
        ),
    ]
