# Generated by Django 5.1.4 on 2025-01-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="bachelor_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="students/bachelor/certificate/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="bachelor_transcript",
            field=models.FileField(
                blank=True, null=True, upload_to="students/bachelor/transcript/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="bank_statement",
            field=models.FileField(blank=True, upload_to="students/bank/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="hsc_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="students/hsc/certificate/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="hsc_transcript",
            field=models.FileField(
                blank=True, null=True, upload_to="students/hsc/transcript/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="language_certificate",
            field=models.FileField(null=True, upload_to="students/language/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="masters_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="students/masters/certificate/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="masters_transcript",
            field=models.FileField(
                blank=True, null=True, upload_to="students/masters/transcript/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ssc_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="students/ssc/certificate/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ssc_transcript",
            field=models.FileField(
                blank=True, null=True, upload_to="students/ssc/transcript/"
            ),
        ),
    ]
