# Generated by Django 5.1.4 on 2025-01-04 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_rename_subejects_subjects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="primarystatus",
            name="application",
        ),
        migrations.RemoveField(
            model_name="secondarystatus",
            name="application",
        ),
        migrations.AddField(
            model_name="application",
            name="p_status",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.primarystatus",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="s_status",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.secondarystatus",
            ),
            preserve_default=False,
        ),
    ]
